const apiKey = process.env.REACT_APP_YOUTUBE_API_KEY;
export const YOUTUBE_POPULAR_VIDEOS_API = "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&regionCode=AU&maxResults=16&key="+apiKey
export const YOUTUBE_CHANNEL_BASE_API = "https://youtube.googleapis.com/youtube/v3/channels?part=snippet%2CcontentDetails%2Cstatistics"
export const SINGLE_VIDEO_BASE_API  = "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics"
export const YOUTUBE_SEARCH_SUGGESTIONS_API = "http://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q="
export const nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
];
export const randomDialogues = [
    { name: "Iron Man", message: "I am Iron Man." },
    { name: "Hulk", message: "Hulk, smash!" },
    { name: "Captain America", message: "I can do this all day." },
    { name: "Bruce Banner", message: "I'm always angry." },
    { name: "Groot", message: "We are Groot." },
    { name: "Hulk", message: "Puny god." },
    { name: "Thanos", message: "I am inevitable." },
    { name: "T'Challa", message: "Wakanda forever!" },
    { name: "Doctor Strange", message: "Dormammu, I've come to bargain." },
    { name: "Thor", message: "The sun will shine on us again." },
    { name: "Thor", message: "I choose to run towards my problems." },
    { name: "Loki", message: "I am burdened with glorious purpose." },
    { name: "Thor", message: "He's a friend from work!" },
    { name: "Captain America", message: "I'm just a kid from Brooklyn." },
    { name: "Sam Wilson", message: "On your left." },
    { name: "Captain America", message: "Language!" },
    { name: "Captain America", message: "I had a date." },
    { name: "Captain America", message: "You get hurt, hurt 'em back. You get killed, walk it off." },
    { name: "Captain Marvel", message: "I have nothing to prove to you." },
    { name: "Groot", message: "I am Groot." },
    { name: "Eddard Stark", message: "The man who passes the sentence should swing the sword." },
    { name: "Tyrion Lannister", message: "I drink and I know things." },
    { name: "Daenerys Targaryen", message: "I am not a queen. I am a Khaleesi." },
    { name: "Jaime Lannister", message: "The things I do for love." },
    { name: "Cersei Lannister", message: "When you play the game of thrones, you win or you die." },
    { name: "Jorah Mormont", message: "There is no cure for being a coward." },
    { name: "Arya Stark", message: "Valar Morghulis." },
    { name: "Joffrey Baratheon", message: "Everyone is mine to torment!" },
    { name: "Jaime Lannister", message: "The things I do for love." },
    { name: "Bran Stark", message: "Chaos is a ladder." },
    { name: "Olenna Tyrell", message: "Tell Cersei. I want her to know it was me." },
    { name: "Brienne of Tarth", message: "Nothing’s more hateful than failing to protect the one you love." },
    { name: "Petyr Baelish", message: "Chaos isn’t a pit. Chaos is a ladder." },
    { name: "Robert Baratheon", message: "I'm not trying to honor you. I'm trying to get you to run my kingdom." },
    { name: "Bronn", message: "There's no cure for being a c**t." },
    { name: "Margaery Tyrell", message: "I want to be the queen." },
    { name: "Stannis Baratheon", message: "The night is dark and full of terrors." },
    { name: "Samwell Tarly", message: "I'm not nothing anymore." },
    { name: "Varys", message: "Power resides where men believe it resides." },
    { name: "Robb Stark", message: "The Lannisters send their regards." },
    { name: "Walter White", message: "I am the one who knocks!" },
    { name: "Jesse Pinkman", message: "Yeah, science!" },
    { name: "Walter White", message: "Say my name." },
    { name: "Gus Fring", message: "I hide in plain sight, same as you." },
    { name: "Saul Goodman", message: "You don't need a criminal lawyer. You need a criminal lawyer." },
    { name: "Walter White", message: "I did it for me. I liked it. I was good at it." },
    { name: "Jesse Pinkman", message: "Yo, Gatorade me, bitch!" },
    { name: "Mike Ehrmantraut", message: "No more half measures." },
    { name: "Hank Schrader", message: "My name is ASAC Schrader, and you can go f**k yourself." },
    { name: "Walter White", message: "Tread lightly." },
    { name: "Skyler White", message: "I can't remember the last time I was happy." },
    { name: "Jesse Pinkman", message: "What’s the point of being an outlaw when you got responsibilities?" },
    { name: "Walter White", message: "I’m in the empire business." },
    { name: "Walter White", message: "I won." },
    { name: "Gus Fring", message: "I will kill your wife, I will kill your son, I will kill your infant daughter." },
    { name: "Jesse Pinkman", message: "Yo, yo, yo, 1-4-8, 3 to the 3 to the 6 to the 9, representin' the ABQ!" },
    { name: "Walter White", message: "You’re goddamn right." },
    { name: "Jesse Pinkman", message: "This is my own private domicile and I will not be harassed!" },
    { name: "Hector Salamanca", message: "Family is all." },
    { name: "Walter White", message: "Chemistry is the study of change." }
];
  
  
  